Pipe error messages to stderr

diff --git a/bin/uau b/bin/uau
--- a/bin/uau
+++ b/bin/uau
@@ -18,7 +18,7 @@ UACONF=/etc/unattended-arch-upgrade.conf
 
 # source the necessary conf
 if [ ! -f $UACONF ]; then
-    echo "ERROR: MISSING $UACONF!!!" 2>&1
+    echo "ERROR: MISSING $UACONF!!!" >&2
     exit 3
 fi
 # shellcheck disable=SC1090
diff --git a/bin/uau-archnews b/bin/uau-archnews
--- a/bin/uau-archnews
+++ b/bin/uau-archnews
@@ -15,7 +15,7 @@ export TERM=non-interactive
 
 # source the necessary conf
 if [ ! -f $UACONF ]; then
-    echo "ERROR: MISSING $UACONF!!!" 2>&1
+    echo "ERROR: MISSING $UACONF!!!" >&2
     exit 3
 fi
 # shellcheck disable=1090
